### ISSUE TITLE
AZ CLI is not available - Workaround

### ISSUE THREAD

**Issue by xolotlatoani** [glconti/insomnia-plugin-azure-keyvault-secrets#3]
OS: OSX

Error: CredentialUnavailableError: Azure CLI could not be found

For some reason, Insomnia does not have my PATH available. IDK if this is a known issue.

Workaround: use the terminal to open Insomnia and PATH will be available and this plugin will work.

BTW: I had to modify some code to make the error visible. Might make a PR if that is ok.

**Comment by glconti** [comment]
I will close this issue since it seems there's an underlying potential improvement in https://github.com/Kong/insomnia/issues/6027
